services:
  api:
    container_name: evolution_api
    image: ghcr.io/ai-chat-os/evolution-api:v2.2.1-redis-on
    restart: always
    depends_on:
      - redis
      - postgres
    environment:
      # 1- Add the Env key values pair to /etc/environment file
      # 2- Run source /etc/environment
      # 3- Run env |grep -i relic; to validate it being loaded.
      # 4- If didn't, CTRL+d to logout
      # 5- Login to the server
      # 6- Run env |grep -i relic again;
      CACHE_REDIS_URI: redis://redis:6379/6
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_NO_CONFIG_FILE: true
      NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: true
      NEW_RELIC_LOG: stdout
      NODE_ENV: PROD
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:7.4.2-alpine
    networks:
      - evolution-net
    container_name: redis
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data

  postgres:
    container_name: postgres
    build:
      context: .postgres/
    networks:
      - evolution-net
    command: ["postgres", "-c", "max_connections=1000", "-c", "listen_addresses=*"]
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=nGYh5UIg4cg9Xwec1AeJ
      - POSTGRES_DB=evolution
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  evolution_instances:
  postgres_data:
  evolution_redis:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge
